export enum LocalStorageKeys {
  Theme = "HitSpooner_Theme",
  UpdateInterval = "HitSpooner_UpdateInterval",
  HitSearchFilters = "HitSpooner_HitSearchFilters",
  TaskViewPanelSizes = "HitSpooner_TaskViewPanelSizes",
  WorkspacePanelSizes = "HitSpooner_WorkspacePanelSizes",
  BlockedRequesters = "HitSpooner_BlockedRequesters",
  FavoriteRequesters = "HitSpooner_FavoriteRequesters",
  WorkspaceListSizes = "HitSpooner_WorkspaceListSizes",
  WorkspaceAvailableColumns = "HitSpooner_WorkspaceAvailableColumns",
  WorkspaceUnavailableColumns = "HitSpooner_WorkspaceUnavailableColumns",
  RequesterModalColumns = "HitSpooner_RequesterModalColumns",
  SoundEnabled = "HitSpooner_SoundEnabled",
  SoundType = "HitSpooner_SoundType",
  SpeechVoiceURI = "HitSpooner_SpeechVoiceURI",
  SpeechRate = "HitSpooner_SpeechRate",
}
